# Generated by Django 5.0.6 on 2024-06-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='content',
            new_name='body',
        ),
    ]
