# Generated by Django 5.0.6 on 2024-06-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_number_of_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views_count',
            new_name='number_of_views',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='is_published',
            new_name='publication_sing',
        ),
    ]
