# Generated by Django 4.2.2 on 2024-07-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_ad'), 'permissions': [('can_edit', 'Can edit category'), ('can_edit_description', 'Can edit description')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
