# Generated by Django 4.2.2 on 2024-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_ad'), 'permissions': [('can_edit', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('change_current_version', 'Can change current_version')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='current_version',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
