# Generated by Django 4.2.2 on 2024-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_current_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_ad'), 'permissions': [('can_edit', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('can_edit_is_published', 'Can edit is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_version',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Публикация'),
        ),
    ]
