# Generated by Django 4.2.2 on 2024-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_remove_product_current_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_ad'), 'permissions': [('can_edit_category', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('can_edit_is_published', 'Can edit is_published')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
